//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Admin.PlayerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayerService.IPlayerService")]
    public interface IPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddExposablePlayer", ReplyAction="http://tempuri.org/IPlayerService/AddExposablePlayerResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ContactInformation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ContactInformation>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.EmailAddress))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.EmailAddress>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PhoneNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.PhoneNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.DateOfBirth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.DateOfBirth>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.Name>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.TeamName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.TeamName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Assist>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchMinute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchMinute>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Card>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ArenaName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ArenaName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDateAndTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDateAndTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDuration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDuration>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameProtocol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameProtocol>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Goal>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.OverTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.OverTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Penalty>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.ShirtNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.StringComparison))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Person))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Name))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.ShirtNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Value_Objects.PlayerEvents>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CardType))]
        void AddExposablePlayer(object player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddExposablePlayer", ReplyAction="http://tempuri.org/IPlayerService/AddExposablePlayerResponse")]
        System.Threading.Tasks.Task AddExposablePlayerAsync(object player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddPlayer", ReplyAction="http://tempuri.org/IPlayerService/AddPlayerResponse")]
        void AddPlayer(Domain.Entities.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddPlayer", ReplyAction="http://tempuri.org/IPlayerService/AddPlayerResponse")]
        System.Threading.Tasks.Task AddPlayerAsync(Domain.Entities.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddPlayerFromList", ReplyAction="http://tempuri.org/IPlayerService/AddPlayerFromListResponse")]
        void AddPlayerFromList(Domain.Entities.Player[] players);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddPlayerFromList", ReplyAction="http://tempuri.org/IPlayerService/AddPlayerFromListResponse")]
        System.Threading.Tasks.Task AddPlayerFromListAsync(Domain.Entities.Player[] players);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddExposablePlayerFromList", ReplyAction="http://tempuri.org/IPlayerService/AddExposablePlayerFromListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ContactInformation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ContactInformation>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.EmailAddress))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.EmailAddress>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PhoneNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.PhoneNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.DateOfBirth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.DateOfBirth>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.Name>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.TeamName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.TeamName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Assist>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchMinute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchMinute>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Card>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ArenaName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ArenaName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDateAndTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDateAndTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDuration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDuration>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameProtocol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameProtocol>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Goal>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.OverTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.OverTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Penalty>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.ShirtNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.StringComparison))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Person))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Name))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.ShirtNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Value_Objects.PlayerEvents>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CardType))]
        void AddExposablePlayerFromList(object[] players);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AddExposablePlayerFromList", ReplyAction="http://tempuri.org/IPlayerService/AddExposablePlayerFromListResponse")]
        System.Threading.Tasks.Task AddExposablePlayerFromListAsync(object[] players);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/FindById", ReplyAction="http://tempuri.org/IPlayerService/FindByIdResponse")]
        Domain.Entities.Player FindById(System.Guid playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/FindById", ReplyAction="http://tempuri.org/IPlayerService/FindByIdResponse")]
        System.Threading.Tasks.Task<Domain.Entities.Player> FindByIdAsync(System.Guid playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Search", ReplyAction="http://tempuri.org/IPlayerService/SearchResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ContactInformation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ContactInformation>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.EmailAddress))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.EmailAddress>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PhoneNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.PhoneNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.DateOfBirth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.DateOfBirth>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.Name>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.TeamName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.TeamName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Assist>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchMinute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchMinute>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Card>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ArenaName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ArenaName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDateAndTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDateAndTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDuration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDuration>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameProtocol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameProtocol>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Goal>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.OverTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.OverTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Penalty>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.ShirtNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.StringComparison))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Person))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Name))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.ShirtNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Value_Objects.PlayerEvents>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CardType))]
        object[] Search(string searchText, System.StringComparison comp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Search", ReplyAction="http://tempuri.org/IPlayerService/SearchResponse")]
        System.Threading.Tasks.Task<object[]> SearchAsync(string searchText, System.StringComparison comp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetAllExposablePlayers", ReplyAction="http://tempuri.org/IPlayerService/GetAllExposablePlayersResponse")]
        Domain.Entities.Player[] GetAllExposablePlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetAllExposablePlayers", ReplyAction="http://tempuri.org/IPlayerService/GetAllExposablePlayersResponse")]
        System.Threading.Tasks.Task<Domain.Entities.Player[]> GetAllExposablePlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetAllPlayers", ReplyAction="http://tempuri.org/IPlayerService/GetAllPlayersResponse")]
        Domain.Entities.Player[] GetAllPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetAllPlayers", ReplyAction="http://tempuri.org/IPlayerService/GetAllPlayersResponse")]
        System.Threading.Tasks.Task<Domain.Entities.Player[]> GetAllPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopAssistsForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopAssistsForSeriesResponse")]
        Domain.Entities.PlayerStats[] GetTopAssistsForSeries(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopAssistsForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopAssistsForSeriesResponse")]
        System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopAssistsForSeriesAsync(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopRedCardsForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopRedCardsForSeriesResponse")]
        Domain.Entities.PlayerStats[] GetTopRedCardsForSeries(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopRedCardsForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopRedCardsForSeriesResponse")]
        System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopRedCardsForSeriesAsync(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopScorersForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopScorersForSeriesResponse")]
        Domain.Entities.PlayerStats[] GetTopScorersForSeries(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopScorersForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopScorersForSeriesResponse")]
        System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopScorersForSeriesAsync(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopYellowCardsForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopYellowCardsForSeriesResponse")]
        Domain.Entities.PlayerStats[] GetTopYellowCardsForSeries(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTopYellowCardsForSeries", ReplyAction="http://tempuri.org/IPlayerService/GetTopYellowCardsForSeriesResponse")]
        System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopYellowCardsForSeriesAsync(System.Guid seriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/SetShirtNumber", ReplyAction="http://tempuri.org/IPlayerService/SetShirtNumberResponse")]
        void SetShirtNumber(System.Guid playerId, Domain.Entities.ShirtNumber newShirtNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/SetShirtNumber", ReplyAction="http://tempuri.org/IPlayerService/SetShirtNumberResponse")]
        System.Threading.Tasks.Task SetShirtNumberAsync(System.Guid playerId, Domain.Entities.ShirtNumber newShirtNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AssignPlayerToTeam", ReplyAction="http://tempuri.org/IPlayerService/AssignPlayerToTeamResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ContactInformation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ContactInformation>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.EmailAddress))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.EmailAddress>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PhoneNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.PhoneNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.DateOfBirth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.DateOfBirth>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.Name>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.TeamName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.TeamName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.PlayerEvents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Assist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Assist>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchMinute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchMinute>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Card))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Card>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ArenaName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.ArenaName>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDateAndTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDateAndTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.MatchDuration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.MatchDuration>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameProtocol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameProtocol>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Goal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Goal>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.OverTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.OverTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.Penalty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.Penalty>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.GameResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Value_Objects.GameResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.AggregatedPlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Value_Objects.ValueObject<Domain.Entities.ShirtNumber>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.StringComparison))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Person))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Name))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Game))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.ShirtNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.Player[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Domain.Entities.PlayerStats[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Value_Objects.PlayerEvents>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.Guid, Domain.Entities.PlayerStats>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlayerStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CardType))]
        void AssignPlayerToTeam(object exposablePlayer, System.Guid teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/AssignPlayerToTeam", ReplyAction="http://tempuri.org/IPlayerService/AssignPlayerToTeamResponse")]
        System.Threading.Tasks.Task AssignPlayerToTeamAsync(object exposablePlayer, System.Guid teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/RemovePlayer", ReplyAction="http://tempuri.org/IPlayerService/RemovePlayerResponse")]
        void RemovePlayer(System.Guid playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/RemovePlayer", ReplyAction="http://tempuri.org/IPlayerService/RemovePlayerResponse")]
        System.Threading.Tasks.Task RemovePlayerAsync(System.Guid playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerServiceChannel : FootballManager.Admin.PlayerService.IPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerServiceClient : System.ServiceModel.ClientBase<FootballManager.Admin.PlayerService.IPlayerService>, FootballManager.Admin.PlayerService.IPlayerService {
        
        public PlayerServiceClient() {
        }
        
        public PlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddExposablePlayer(object player) {
            base.Channel.AddExposablePlayer(player);
        }
        
        public System.Threading.Tasks.Task AddExposablePlayerAsync(object player) {
            return base.Channel.AddExposablePlayerAsync(player);
        }
        
        public void AddPlayer(Domain.Entities.Player player) {
            base.Channel.AddPlayer(player);
        }
        
        public System.Threading.Tasks.Task AddPlayerAsync(Domain.Entities.Player player) {
            return base.Channel.AddPlayerAsync(player);
        }
        
        public void AddPlayerFromList(Domain.Entities.Player[] players) {
            base.Channel.AddPlayerFromList(players);
        }
        
        public System.Threading.Tasks.Task AddPlayerFromListAsync(Domain.Entities.Player[] players) {
            return base.Channel.AddPlayerFromListAsync(players);
        }
        
        public void AddExposablePlayerFromList(object[] players) {
            base.Channel.AddExposablePlayerFromList(players);
        }
        
        public System.Threading.Tasks.Task AddExposablePlayerFromListAsync(object[] players) {
            return base.Channel.AddExposablePlayerFromListAsync(players);
        }
        
        public Domain.Entities.Player FindById(System.Guid playerId) {
            return base.Channel.FindById(playerId);
        }
        
        public System.Threading.Tasks.Task<Domain.Entities.Player> FindByIdAsync(System.Guid playerId) {
            return base.Channel.FindByIdAsync(playerId);
        }
        
        public object[] Search(string searchText, System.StringComparison comp) {
            return base.Channel.Search(searchText, comp);
        }
        
        public System.Threading.Tasks.Task<object[]> SearchAsync(string searchText, System.StringComparison comp) {
            return base.Channel.SearchAsync(searchText, comp);
        }
        
        public Domain.Entities.Player[] GetAllExposablePlayers() {
            return base.Channel.GetAllExposablePlayers();
        }
        
        public System.Threading.Tasks.Task<Domain.Entities.Player[]> GetAllExposablePlayersAsync() {
            return base.Channel.GetAllExposablePlayersAsync();
        }
        
        public Domain.Entities.Player[] GetAllPlayers() {
            return base.Channel.GetAllPlayers();
        }
        
        public System.Threading.Tasks.Task<Domain.Entities.Player[]> GetAllPlayersAsync() {
            return base.Channel.GetAllPlayersAsync();
        }
        
        public Domain.Entities.PlayerStats[] GetTopAssistsForSeries(System.Guid seriesId) {
            return base.Channel.GetTopAssistsForSeries(seriesId);
        }
        
        public System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopAssistsForSeriesAsync(System.Guid seriesId) {
            return base.Channel.GetTopAssistsForSeriesAsync(seriesId);
        }
        
        public Domain.Entities.PlayerStats[] GetTopRedCardsForSeries(System.Guid seriesId) {
            return base.Channel.GetTopRedCardsForSeries(seriesId);
        }
        
        public System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopRedCardsForSeriesAsync(System.Guid seriesId) {
            return base.Channel.GetTopRedCardsForSeriesAsync(seriesId);
        }
        
        public Domain.Entities.PlayerStats[] GetTopScorersForSeries(System.Guid seriesId) {
            return base.Channel.GetTopScorersForSeries(seriesId);
        }
        
        public System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopScorersForSeriesAsync(System.Guid seriesId) {
            return base.Channel.GetTopScorersForSeriesAsync(seriesId);
        }
        
        public Domain.Entities.PlayerStats[] GetTopYellowCardsForSeries(System.Guid seriesId) {
            return base.Channel.GetTopYellowCardsForSeries(seriesId);
        }
        
        public System.Threading.Tasks.Task<Domain.Entities.PlayerStats[]> GetTopYellowCardsForSeriesAsync(System.Guid seriesId) {
            return base.Channel.GetTopYellowCardsForSeriesAsync(seriesId);
        }
        
        public void SetShirtNumber(System.Guid playerId, Domain.Entities.ShirtNumber newShirtNumber) {
            base.Channel.SetShirtNumber(playerId, newShirtNumber);
        }
        
        public System.Threading.Tasks.Task SetShirtNumberAsync(System.Guid playerId, Domain.Entities.ShirtNumber newShirtNumber) {
            return base.Channel.SetShirtNumberAsync(playerId, newShirtNumber);
        }
        
        public void AssignPlayerToTeam(object exposablePlayer, System.Guid teamId) {
            base.Channel.AssignPlayerToTeam(exposablePlayer, teamId);
        }
        
        public System.Threading.Tasks.Task AssignPlayerToTeamAsync(object exposablePlayer, System.Guid teamId) {
            return base.Channel.AssignPlayerToTeamAsync(exposablePlayer, teamId);
        }
        
        public void RemovePlayer(System.Guid playerId) {
            base.Channel.RemovePlayer(playerId);
        }
        
        public System.Threading.Tasks.Task RemovePlayerAsync(System.Guid playerId) {
            return base.Channel.RemovePlayerAsync(playerId);
        }
    }
}
